Update provenance
BCCDC-PHL/tbprofiler-nf pull request #27
Opened 2024-02-07 02:05 UTC by taranewman

Adding provenance in the same format as BCCDC-PHL/kma-cgmlst

Format may still be adjusted to add name and and flag and optional description variable.

TBD: BCCDC-PHL/pipeline-provenance-schema

2024-02-07 20:21 UTC, dfornika commented
This is looking great. Could you add a section to the README that describes the format of the provenance file? See the kma-cgmlst README for an example. Please be sure not to include any real sample IDs in the example (just replace with `sample-01` or similar)

https://github.com/BCCDC-PHL/kma-cgmlst?tab=readme-ov-file#provenance

2024-02-07 20:21 UTC, dfornika requested changes

2024-02-07 21:59 UTC, taranewman commented on modules/tbprofiler.nf
> +    printf -- "          value: ${reads_2}\\n"           >> ${sample_id}_tbprofiler_provenance.yml
removed!

2024-02-08 02:12 UTC, dfornika approved these changes

2024-02-08 02:27 UTC, merged